#!/usr/bin/env bash
#clock that displays hours 0-12 and minutes
h=0
m=1
while [ $h -le 12 ]
do
    echo "Hour: $h"
    while [ $m -le 60 ]
    do
	if [ $m -eq 60 ]
	then
	    m=1
	    break
	else
	    echo $m
	fi
	m=$(( m + 1 ))
    done
    h=$(( h + 1 ))
done

	
